EXTRA_DIST = examples \
             doc/programming.pdf \
             doc/compilation.pdf \
             doc/FAQ.pdf \
             doc/CODE_OF_CONDUCT.pdf \
             doc/srs.pdf doc/srs.markdown \
             doc/sds.pdf doc/feenox-manual.pdf


TESTS = \
        tests/abort.sh \
        tests/algebraic_expr.sh \
        tests/builtin.sh \
        tests/cylinder-traction-force.sh \
        tests/default_argument_value.sh \
        tests/expressions_constants.sh \
        tests/expressions_variables.sh \
        tests/expressions_functions.sh \
        tests/exp.sh \
        tests/i-beam-euler-bernoulli.sh \
        tests/iaea-pwr.sh \
        tests/iterative.sh \
        tests/fit.sh \
        tests/function_algebraic.sh \
        tests/function_data.sh \
        tests/function_file.sh \
        tests/function_vectors.sh \
        tests/integral.sh \
        tests/laplace2d.sh \
        tests/materials.sh \
        tests/mesh.sh \
        tests/modal.sh \
        tests/nafems-le1.sh \
        tests/nafems-le10.sh \
        tests/nafems-t1-4.sh \
        tests/nafems-t2-3.sh \
        tests/neutron_diffusion_src.sh \
        tests/neutron_diffusion_keff.sh \
        tests/parallelepiped.sh \
        tests/point-kinetics.sh \
        tests/thermal-1d.sh \
        tests/thermal-2d.sh \
        tests/trig.sh \
        tests/vector.sh

XFAIL_TESTS = tests/abort.sh         

DISTCLEANFILES = \
                 config.guess \
                 compile \
                 depcomp \
                 install-sh \
                 config.sub \
                 test-driver \
                 missing \
                 feenox \
                 tests/function_vectors1d.last \
                 tests/nafems-le10.msh \
                 tests/fit1d_gradient.last \
                 tests/fibo_vector.last \
                 tests/fibo_formula.last \
                 tests/expressions_variables.last \
                 tests/nafems-le10.last \
                 tests/square-centered.msh \
                 tests/2dpwr-eighth.msh \
                 tests/nafems-t4.msh \
                 tests/find_extrema2d.last \
                 tests/algebraic_expr.last \
                 tests/2dpwr-quarter.msh \
                 tests/fibo_iterative.last \
                 tests/parallelepiped.msh \
                 mesh2d.msh \
                 laplace-square.msh

all-local:
	cp -r src/feenox$(EXEEXT) .

# clean-local: code-coverage-clean
# distclean-local: code-coverage-dist-clean
