dist_doc_DATA = AUTHORS ChangeLog README TODO \
                doc/CODE_OF_CONDUCT.md \
                doc/feenox.xml \
                doc/programming.md \
                doc/FAQ.md \
                doc/syntax-kate.sh \
                doc/syntax-tex.sh

dist_man_MANS = doc/feenox.1

EXTRA_DIST = examples

TESTS = \
        tests/abort.sh \
        tests/algebraic_expr.sh \
        tests/builtin.sh \
        tests/default_argument_value.sh \
        tests/expressions_constants.sh \
        tests/expressions_variables.sh \
        tests/expressions_functions.sh \
        tests/exp.sh \
        tests/iterative.sh \
        tests/iaea-pwr.sh \
        tests/fit.sh \
        tests/function_algebraic.sh \
        tests/function_data.sh \
        tests/function_file.sh \
        tests/function_vectors.sh \
        tests/integral.sh \
        tests/laplace2d.sh \
        tests/materials.sh \
        tests/mesh.sh \
        tests/modal.sh \
        tests/nafems-lex.sh \
        tests/nafems-tx.sh \
        tests/nafems-t4.sh \
        tests/neutron_diffusion_src.sh \
        tests/neutron_diffusion_keff.sh \
        tests/parallelepiped.sh \
        tests/point-kinetics.sh \
        tests/thermal-1d.sh \
        tests/thermal-2d.sh \
        tests/trig.sh \
        tests/vector.sh

XFAIL_TESTS = tests/abort.sh         

DISTCLEANFILES = \
                 config.guess \
                 compile \
                 depcomp \
                 install-sh \
                 config.sub \
                 test-driver \
                 missing \
                 feenox \
                 tests/function_vectors1d.last \
                 tests/nafems-le10.msh \
                 tests/fit1d_gradient.last \
                 tests/fibo_vector.last \
                 tests/fibo_formula.last \
                 tests/expressions_variables.last \
                 tests/nafems-le10.last \
                 tests/square-centered.msh \
                 tests/2dpwr-eighth.msh \
                 tests/nafems-t4.msh \
                 tests/find_extrema2d.last \
                 tests/algebraic_expr.last \
                 tests/2dpwr-quarter.msh \
                 tests/fibo_iterative.last \
                 mesh2d.msh \
                 laplace-square.msh

all-local:
	cp -r src/feenox$(EXEEXT) .

# clean-local: code-coverage-clean
# distclean-local: code-coverage-dist-clean
